### PR TITLE
add world-space FlxCamera rotation

### PR DESCRIPTION
**Pull request by cyn0x8**
implementation of world-space `FlxCamera` rotation via a new `rotation:Float` property (rotates about the center)

uses a new `_rotationCanvas:Sprite` to not interfere with current `canvas` behavior or whatever people might be doing with it

https://github.com/user-attachments/assets/5518267a-85e0-4a7e-b735-94d83702e52c

> [!note]
> this is my first pr here!! criticism and suggestions and changes are appreciated...
> (especially on the margin calculation since the math was kinda figured out by trial & error)

### CODE REVIEW

**Comment by richTrash21** [comment]
is there a reason why `Sprite.__transform` is used for rotation instead of `Sprite.rotation`? it also seems to break the flash target

**Comment by DetectiveBaldi** [comment]
i think there was an attempt to do this in #2679, but from what i could tell there was an issue where objects would havebeen visible at a certain rotation weren't
does this pr address this?

**Comment by cyn0x8** [comment]
> i think there was an attempt to do this in #2679, but from what i could tell there was an issue where objects that would have been visible at a certain rotation, weren't does this pr address this?

yes, with the margin changes

**Comment by cyn0x8** [comment]
> is there a reason why `Sprite.__transform` is used for rotation instead of `Sprite.rotation`? it also seems to break the flash target

`Sprite.rotation` seemed to be rotating it about the top left corner rather than the center when i was changing it? unsure if that was just a quirk in my test or not... but regardless im guessing itd be more performant than the matrix math so tomorrow ill try using that + translating the sprite to re-center the rotation

also i saw (before the workflow disappeared??) that `Sprite.__transform` doesnt seem to be present on flash target! changing to `Sprite.rotation` would fix that as well

**Comment by richTrash21** [comment]
> `Sprite.rotation` seemed to be rotating it about the top left corner rather than the center when i was changing it?

tested this myself and this problem was present. in that case it might be useful to look into `Sprite.transform`. using it's `matrix` variable i successfully recreated the rotation effect. this variable is also present in the flash target so theoretically it might also fix the flash target (can't say for sure because i didn't test it on flash).

one more thing: while testing i encountered a bug with resizing the window (affects fullscreen too). it seems to misplace the camera if `rotation` set to any value except `0`

**Comment by Geokureli** [comment]
FYI, we have a proposed way to introduce world-rotation, already, here: https://github.com/HaxeFlixel/flixel/issues/2715
the idea is that we will be able to nest objects within objects that when rotated, rotate all the objects nested inside, as a bonus, this will allow us to easily apply the same transformations to the camera as well. Note in the section labelled "Advantages":
> We could also give camera's a DrawContext, or its own orientation and color rendering information, that is applied to all sprites rendered to it, allowing cameras to have rotation (related to https://github.com/HaxeFlixel/flixel/pull/2679)

It'll take longer to implement, but I'd rather go this route than make some adhoc field, like this.

I have to assume this is kind of a cheat that doesn't honor properties like `sprite.isOnScreen` and therefore wouldn't work with things like FlxBackdrop

**Comment by cyn0x8** [comment]
> FYI, we have a proposed way to introduce world-rotation, already, here: #2715 the idea is that we will be able to nest objects within objects that when rotated, rotate all the objects nested inside, as a bonus, this will allow us to easily apply the same transformations to the camera as well. Note in the section labelled "Advantages":
> 
> > We could also give camera's a DrawContext, or its own orientation and color rendering information, that is applied to all sprites rendered to it, allowing cameras to have rotation (related to #2679)
> 
> It'll take longer to implement, but I'd rather go this route than make some adhoc field, like this.
> 
> I have to assume this is kind of a cheat that doesn't honor properties like `sprite.isOnScreen` and therefore wouldn't work with things like FlxBackdrop

awesome! ill close the pr then

**Pull request closed without merging**
