### PR TITLE
Define dialogs

### PR DESCRIPTION
**Pull request by larsiusprime**
(this makes FlxSaveDialogs muuuuuch cleaner & easier to read)

### CODE REVIEW

**Comment by larsiusprime** [comment]
See: https://github.com/HaxeFlixel/flixel-addons/pull/207

**Comment by MSGhero** [comment]
Didn't openfl or lime make its own system dialog features? Maybe it was planned for the future.

**Comment by larsiusprime** [comment]
So they did... hmmm.

https://github.com/openfl/lime/blob/b6d4093e6b7c4c1bfaa63af53faf4cc3dd862950/lime/ui/FileDialog.hx

https://github.com/openfl/openfl/blob/28984d5e4145f559c46aea2daa0ec9c9fa009508/openfl/net/FileReference.hx

Perhaps we should just use that :D

**Comment by MSGhero** [comment]
There are issues with systools that go into the c source, and it hasn't been updated in forever last I checked.

**Comment by MSGhero** [comment]
I need a breather from implementing big changes to flixel. I'm still in tears about the hscript Travis thing.

**Comment by larsiusprime** [comment]
hah, sorry about that. 

The previous implementation of FlxScreenGrab still used systools; if we move to openfl's native dialogs we can possibly remove all of these dependencies in one go, linc_dialogs and systools.

**Comment by larsiusprime** [comment]
Closing this as I think it's better to use OpenFL's own dialog system as that makes this totally redundant.

**Pull request closed without merging**
