### PR TITLE
Added `pauseAll` to FlxTimer

### PR DESCRIPTION
**Pull request by Tiago-Ling**
It makes easier to control timer behavior across different classes.

### CODE REVIEW

**Comment by Gama11** [comment]
Doesn't setting `FlxTimer.manager.active = false;` do the trick?

**Comment by MSGhero** [comment]
I prefer `pauseAll()` and `resumeAll()` as inlined ^, though idk if there are consequences of doing it that way.

**Comment by Gama11** [comment]
I don't think inlining would make any noticable difference here, this isn't a function you'd typically call very often.

**Comment by MSGhero** [comment]
I guess, but two functions over one imo.

**Comment by Tiago-Ling** [comment]
@Gama11 You're right, you can set active to false. Not very intuitive
actually, only tried it after you pointed it out. So you think there's no
need for this method? If so i can close the pull request.

**Comment by Gama11** [comment]
@Tiago-Ling Yes, seems redundant.

**Pull request closed without merging**
