### PR TITLE
use openfl git version?

### PR DESCRIPTION
**Pull request by Geokureli**
hopefully avoids https://github.com/openfl/lime/issues/1763

### CODE REVIEW

**Comment by player-03** [comment]
Sorry, I misspoke. I meant Lime rather than OpenFL, since that's where the error was fixed.

**Comment by Geokureli** [comment]
> Sorry, I misspoke. I meant Lime rather than OpenFL, since that's where the error was fixed.

damn just now read this after switching to git openfl, lol

**Comment by player-03** [comment]
I ended up testing it myself, and it still doesn't work. setup-flixel sets Lime to version 8.1.1, even if you've already run `haxelib git lime`.

**Comment by Geokureli** [comment]
@player-03, I'm getting this error in CI, now
> \> haxelib run openfl test unit cpp -Dtravis
> Error: Error: Cannot process [format]: Library format is not installed : run 'haxelib install format'

I'm using the following to install lime and openfl
> /> haxelib git lime https://github.com/openfl/lime --quiet --global
> /> haxelib install openfl --quiet --global

this doess not happen when using the latest lime release, format is also not installed on any of flixel's CI jobs

**Comment by player-03** [comment]
Format is required for `lime rebuild tools`, but if you install Lime from Haxelib the tools come prebuilt, so as long as you never rebuild them, you're good.

IIRC its only job is to process SVG icons.

**Comment by Geokureli** [comment]
> Format is required for `lime rebuild tools`, but if you install Lime from Haxelib the tools come prebuilt, so as long as you never rebuild them, you're good.
> 
> IIRC its only job is to process SVG icons.

I'll just install format, anything else I may need?

**Comment by player-03** [comment]
[hxp](https://github.com/openfl/hxp), if you don't have it. Used to be part of Lime, but they decided to split it off.

**Comment by Geokureli** [comment]
> [hxp](https://github.com/openfl/hxp), if you don't have it. Used to be part of Lime, but they decided to split it off.

apparently hxcpp is required, even when not building for cpp targets, is there a workaround for this?

**Comment by player-03** [comment]
> apparently hxcpp is required, even when not building for cpp targets, is there a workaround for this?

Oh right, it also likes to rebuild lime.ndll if that doesn't exist. There are two possible workarounds:

1. Download the latest Haxelib release, and copy over the ndll directory.
2. Specify the `-eval` flag every time you run Lime. (Not sure OpenFL will pass this through, though. It's not considered that important a feature yet.)

> When is the next lime release scheduled, lol

@joshtynjala

**Comment by Geokureli** [comment]
both workarounds seem awfully involved and hacky, I may just wait for a release. Is there any way to make lime work without hxp and hxcpp on non-cpp targets? does it really, actually need both?

**Comment by joshtynjala** [comment]
> >    When is the next lime release scheduled, lol

> @joshtynjala

I guess I can try to find time to do a Lime 8.1.2 release later this month.

**Comment by player-03** [comment]
> I guess I can try to find time to do a Lime 8.1.2 release later this month.

I did a draft of a changelog.

Also, I'm pretty sure the change was included in today's release of Haxe 4.3.4, so this is going to start affecting more people.

**Comment by joshtynjala** [comment]
> Also, I'm pretty sure the change was included in Haxe 4.3.4, so this is going to start affecting more people.

Okay, I'll try my best to do the release sooner rather than later.

**Pull request closed without merging**
