### PR TITLE
FlxBitmapText: add clipRect support

### LINKED ISSUE #2170: clipRect is ignored in FlxBitmapText when FlxG.renderBlit is false
This works on flash but not on targets where `renderBlit` is false. I tried html5, macOS and Neko and got the same result.
```haxe
var sprite = new FlxBitmapText(someFont);
sprite.text = "TEST TEXT";
sprite.clipRect = FlxRect.get(0, 0, sprite.width / 2, sprite.height);
add(sprite);
```

for these targets, clipRect is never referenced anywhere in the draw process

### PR DESCRIPTION
**Pull request by Geokureli**
this change culls and clips letters on the draw() method based on the Text's clipRect property. I'm actively searching for a way to do this on updateTextBitmap rather than on each draw, but that might not be worthwhile.

fixes #2170

### CODE REVIEW

**Comment by Geokureli** [comment]
closing until I rule out possible better solutions

**Comment by Geokureli** [comment]
reopening after some tiny optimizations.

It's no longer checking chars entirely outside of the clipRect, but no matter how I spin it I'll have to check every char that intersects clipRect on every draw call. we could refactor how char frame data is maintained via updateTextBitmap, but screw that noise.

**Comment by Gama11** [comment]
I've tested these changes against the FlxBitmapText demo, and it looks like this produces crashes for some clipRect values (Neko target), such as:

```haxe
tf2.clipRect = new FlxRect(0, 0, 390, tf2.height);
```

```
Called from sys.io.FileOutput::$statics line 1
Called from ApplicationMain::main line 32
Called from ApplicationMain::create line 243
Called from lime.app.Application::exec line 167
Called from lime._internal.backend.native.NativeApplication::exec line 144
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent line 431
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch line 101
Called from openfl.display.Stage::render line 1423
Called from openfl.display.Stage::__broadcastEvent line 1561
Called from openfl.display.Stage::__handleError line 1892
Called from neko.Lib::rethrow line 65
Called from openfl.display.Stage::__broadcastEvent line 1557
Called from openfl.display.DisplayObject::__dispatch line 1236
Called from openfl.events.EventDispatcher::__dispatchEvent line 443
Called from flixel.FlxGame::onEnterFrame line 551
Called from flixel.FlxGame::draw line 854
Called from flixel.FlxState::draw line 70
Called from flixel.group.FlxTypedGroup::draw line 185
Called from flixel.text.FlxBitmapText::draw line 435
Called from openfl.geom.Matrix::translate line 688
Uncaught exception - Invalid operation (+)
```

____

With a width of 400, I also get this weird effect:



It seems the `R` and `E` characters are cut off vertically _and_ horizontally for some reason?

**Comment by Geokureli** [comment]
I've been thinking about this, is there a reason we draw the letters every frame, rather than drawing to an intermediary graphic on text updates? Right now FlxBitmapText is a two-headed beast between renderTile and renderBlit targets, and aligning them would solve #2172 as well

**Comment by Gama11** [comment]
You'd have to ask @Beeblerox why it's implemented the way it is. :)

**Comment by Geokureli** [comment]
@Beeblerox Zaphod, I know your username suggests you're more inclined for things to have 2 heads,  but could you help me wrap my singular head around this?

**Comment by Geokureli** [comment]
I created a [https://gist.github.com/Geokureli/8369b5cc6c3d7972a640d8380736feb0](testbed) using the FLxBitmapText sample where the rect is set via the mouse. Messed with it for a wehile and couldn't break it.

**Comment by Gama11** [comment]
Yep, seems to work a lot more reliably now. Thanks! 👍

**Comment by Beeblerox** [comment]
👍

**Pull request merged**
