### PR TITLE
Move FlxCamera screen-shake movement to updateShake.

### PR DESCRIPTION
**Pull request by bendmorris**
Fixes https://github.com/HaxeFlixel/flixel/issues/1929

### CODE REVIEW

**Comment by bendmorris** [comment]
With this change I don't think _fxShakeOffset is even needed anymore. It's used in `shake` to determine whether another shake is already happening, but that seems wrong, could use _fxShakeDuration for that.

**Comment by Gama11** [comment]
Nice fix, less bugs _and_ less code. ;)

**Comment by MSGhero** [comment]
Travis? https://travis-ci.org/HaxeFlixel/flixel/jobs/159004450#L1484-L1486

Only on dev cpp tho

**Comment by Gama11** [comment]
Yeah, not sure what that's about. That happens every now and then, apparently randomnly. I guess I'll open a separate issue about that because it's getting pretty annoying...

Nothing to do with these changes though!

**Comment by Gama11** [comment]
See #1942.

**Pull request merged**
