### PR TITLE
Added `anyReleased` and `firstReleased` to `FlxKeyManager`.

### PR DESCRIPTION
**Pull request by MAJigsaw77**

### CODE REVIEW

**Comment by Geokureli** [comment]
can you share a practical use for this? or did it seem like something you assume others would want?

**Comment by MAJigsaw77** [comment]
> can you share a practical use for this? or did it seem like something you assume others would want?

I've wanted to use something like this in a project but seem they didn't existed, I added them

**Comment by Geokureli** [comment]
can you give an example?

**Comment by MAJigsaw77** [comment]
> can you give an example?

```haxe
if (FlxG.keys.pressed.DOWN)
	animation.play('down');
else if (FlxG.keys.pressed.UP)
	animation.play('up');

if (FlxG.keys.pressed.LEFT)
	animation.play('left');
else if (FlxG.keys.pressed.RIGHT)
	animation.play('right');

if (FlxG.keys.anyReleased([DOWN, UP, LEFT, RIGHT]))
	animation.finish();
```

**Comment by Geokureli** [comment]
I don't see any practical use for firstReleased, why would anyone want to know the last button released but not the one "just released"?

**Comment by MAJigsaw77** [comment]
Then whats the meaning of using `FlxG.keys.released`?

**Comment by MAJigsaw77** [comment]
Nvm...

**Comment by Geokureli** [comment]
https://github.com/HaxeFlixel/flixel/wiki/Contribution-Guide#creating-new-features

**Pull request closed without merging**
