### PR TITLE
FlxFlicker: clarify docs of duration

### PR DESCRIPTION
**Pull request by ashes999**
I like clarity.

### CODE REVIEW

**Comment by MSGhero** [comment]
I like it. I always have to go back into the source to double check.

**Comment by Gama11** [comment]
Nice, but there's at least two more places where it needs to be added.

**Comment by Gama11** [comment]
Ok, I think I got all of them. Thanks!

**Comment by ashes999** [comment]
@Gama11 thanks for that. I didn't know about the other two locations.

**Pull request merged**
