### PR TITLE
VCRFrontEnd#stopRecording(): add an OpenSaveDialog argument, closes #1725

### LINKED ISSUE #1725: Allow foregoing a save dialog on VCRFrontEnd.stopRecording() with flash target
- **Flixel version:** dev, updated just now
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** flash (d/r)

________________________________

**Code snippet reproducing the issue**:

```haxe
		var save:String = FlxG.vcr.stopRecording();
```

________________________________

**Observed behavior:** A native Save dialog box opens, allowing the user to save the recording.
**Expected behavior:** A way to avoid this, so that I can use the VCR for integration testing.  (Or, suppose you want to handle the data internally, like for an instant replay a la Worms, without saving the file somewhere.)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30972785-allow-foregoing-a-save-dialog-on-vcrfrontend-stoprecording-with-flash-target?utm_campaign=plugin&utm_content=tracker%2F254189&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F254189&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by GimmickyApps**
Default true so as to not break existing code.

### CODE REVIEW

**Comment by Gama11** [comment]
The change looks good to me, not merging for now though - this is still a new feature and as such belongs in 4.1.0. We might want to do a patch release (4.0.1) first to sort out some bugs.

**Comment by GimmickyApps** [comment]
Cool, thanks for explaining :)

**Comment by GimmickyApps** [comment]
It's interesting the Travis build completed.  I was getting a compiler error when trying to use it in a project.

**Comment by Gama11** [comment]
Yeah, that's interesting. The reason is that the failing code only compiles in debug mode and the demos are compiled in release mode.

It's also slipped through the coverage tests (one of them defines `FLX_RECORD`), since debug mode is only activated in the _other_ case...

We might want to think about changing that to debug mode.. We shouldn't really "miss out" on anything with that, it should just compile more code..

**Comment by GimmickyApps** [comment]
For me, the code was failing to compile in debug mode, too.

**Comment by Gama11** [comment]
Actually, I've decided it's probably best to `dev` for the next minor release (`4.1.0`) and a new `patch` branch for the next patch release (4.0.1, if there is one).

**Pull request merged**
