### PR TITLE
Add better support for FlxButton scaling, fixes #2047

### LINKED ISSUE #2047: Can't Change FlxButton Style
- **Haxe version:** 3.4.2
- **Flixel version:** 4.2.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** JS

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		var newGameButton = new FlxButton(0, 0, "Label", function() { });
		// Scale up and set font size appropriately
		 newGameButton.scale.x = newGameButton.scale.y = 3;
		newGameButton.label.setFormat(null, 32);
		newGameButton.label.width *= 3;  
		this.add(newGameButton);
	}
}
```

________________________________

**Observed behavior:**

**Expected behavior:** Non-truncated text

How do I scale up a button, without having to jump through hoops like this?

### PR DESCRIPTION
**Pull request by gcardozo123**
fixes #2047

### CODE REVIEW

**Comment by gcardozo123** [comment]
codeclimate is complaining that I'm using spaces for indentation, if you need me to change that (or anything else) let me know, please.

**Comment by MSGhero** [comment]
It's easiest if you fix them all and anything else codeclimate complains about.

**Comment by gcardozo123** [comment]
@MSGhero now everything is fine with both Travis-ci and Codeclimate. ;)

**Comment by Gama11** [comment]
This causes issues with `systemFont` - it resets the font back to the default Flixel font:

 

Also, I'm not sure if it's a good idea to tie this to `updateHitbox()`, which you'd rarely think to call on a `FlxButton` (since you usually don't need hitboxes / collisions for UI).

**Pull request closed without merging**
