### PR TITLE
FlxSpriteGroup: add insert()

### PR DESCRIPTION
**Pull request by MSGhero**
Basically just `add` with a bit more control over positioning, or a more useful `group.insert()`. May or may not need it for haxeui.

### CODE REVIEW

**Comment by Gama11** [comment]
This is almost a 1:1 copy of `add()`, I'd like to avoid that redundancy.

**Comment by MSGhero** [comment]
I think an optional add parameter would break people's overrides, so a private `addButNotActually()` that just offsets the sprite and all?

**Comment by Gama11** [comment]
Yeah. that's what I meant.

**Comment by MSGhero** [comment]
I can't think of a good function name

**Comment by MSGhero** [comment]
Ok

**Pull request merged**
