### PR TITLE
FlxAnimation: add support for changing frames, closes #1888

### LINKED ISSUE #1888: No way to modify animation frames (without instantiating new animation)
```FlxAnimation._frames``` is private, meaning we cannot edit the frames of an animation after it has already been instantiated. ```FlxAnimationController``` provides methods append frames to an animation, but there is no way to remove or change the frames.

The reason I wish to do this is that I have pooled objects that may require slightly different animations once recycled. Simply using add, however, will be constantly instantiating new ```FlxAnimation``` objects, so I would prefer to avoid this.

Should ```FlxAnimation._frames``` be public, or perhaps we could add a new method to ```FlxAnimationController``` to set the frames of an existing animation?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35887836-no-way-to-modify-animation-frames-without-instantiating-new-animation?utm_campaign=plugin&utm_content=tracker%2F254189&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F254189&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Beeblerox**

### CODE REVIEW

**Comment by Gama11** [comment]
This makes them public, but they're still read-only, so there's no way to set them?

**Comment by Beeblerox** [comment]
But now you can modify this array.

**Comment by Beeblerox** [comment]
And original issue #1888 was about modifying frames array, not setting it

**Comment by Gama11** [comment]
Right.. But why make it `(default, null)` at all then? You can already modify it, might as well allow assignment too. Often times assigning an array literal directly is more convenient.

**Comment by Beeblerox** [comment]
ok, let it be writable too.

**Pull request merged**
