### PR TITLE
Make FlxRandom portable

### LINKED ISSUE #2469: Make FlxRandom portable
After some digging, it seems like `FlxRandom.hx` might be the best cross-platform RNG implementation in pure Haxe. I actually want to use it for projects that go beyond HaxeFlixel -- but this doesn't work currently because FlxRandom.hx references flash types (all indirectly, through FlxG, FlxSprite, etc.)

By editing the source directly in my haxelib folder, I was able to add just a few `#if flash` directives that made it possible for me to add `-lib flixel` to a non-flixel project and import FlxRandom for my purposes. Maybe this would be useful to others too? Would a PR be welcome for this?

### PR DESCRIPTION
**Pull request by NQNStudios**
This adds a few `#if flash` directives, allowing the FlxRandom class to be imported by projects that aren't HaxeFlixel games.

Close #2469

### CODE REVIEW

**Comment by Geokureli** [comment]
These aren't flash only features they're available on all platforms, so by adding these conditionals you're breaking all non flash targets.

 Note that `flash.geom.Rectangle` actually points to `openfl.geom.Rectangle` on non-flash targets:
 https://github.com/openfl/openfl/blob/develop/lib/flash-externs/src/flash/geom/Rectangle.hx#L37
 
 There's plenty of standalone random number generating haxelibs, already. I'm not convinced that it's worthwhile to make FlxRandom standalone

**Comment by NQNStudios** [comment]
In going through all the other RNG haxelibs, I saw that none of them have had commits within the last year. I'm hoping to use one that is being maintained, which HaxeFlixel is. And I could copy and modify the code, but that brings up a licensing mismatch with my codebase, and would make it harder to contribute back any improvements I might make.

What about using `#if (flash || openfl)`?

**Comment by Geokureli** [comment]
FlxRandom is such a tiny class and it's under MIT, you could literally just make a new haxelib, change a couple names, remove flixel refs and put any license on it. At most maybe put a blurb in the documentation about how it came from HaxeFlixel. there's plenty of classes in the flixel engine that say it was stolen from other libs.

I don't think flixel should worry about the "portability" of it's tiny features and I don't recommend using flixel just for FlxRandom

**Comment by NQNStudios** [comment]
OK thank you for the licensing advice!

**Pull request closed without merging**
