### PR TITLE
Make FlxAnimationController.callback an FlxTypedSignal

### PR DESCRIPTION
**Pull request by richTrash21**
Closes: #3204

~~Maybe there's a better way to name FlxTypedSignal variables.~~
Thanks Geo!

### CODE REVIEW

**Comment by DetectiveBaldi** [comment]
@Geokureli is there a reason in certain cases flixel has an private signal for certain functionality, and then a public one (which is just a getter for the internal one)
this is seen in FlxState https://github.com/HaxeFlixel/flixel/blob/dev/flixel%2FFlxState.hx#L92 and also seems to be adopted here

**Comment by Geokureli** [comment]
> @Geokureli is there a reason in certain cases flixel has an private signal for certain functionality, and then a public one (which is just a getter for the internal one) this is seen in FlxState

This is likely a leftover from the flash Flixel, where this was common practice (for good reason) but it has little advantage in haxe

**Comment by Geokureli** [comment]
Changes:
- Rename `finishedCallback` to `onFinish` and `frameCallback` to `onFrameChange`
- Remove private versions of both and getters/setters, this is almost never needed since you can just use `var foo(default, null)` to prevent external write-access. I also removed the instantiation in the getters, I'm strongly against that practice
- Made the signals `final` (The new standard for signals now that code climate allows it)
- Add unit tests
- Improve documentation
- convert signal types from `A->B->Void` to `(a:A, b:B)->Void` for better code completion and readability

**Comment by Geokureli** [comment]
Not sure why cpp unit tests are failing and the error is not helpful, gonna look into this, may need to revert unit tests for now, iunno

**Comment by Geokureli** [comment]
Found the cause of failing CI: https://github.com/HaxeFoundation/hxcpp/pull/1125

**Pull request merged**
