### PR TITLE
Added null check in stop function to prevent crash issues.

### PR DESCRIPTION
**Pull request by TheoDevelops**
Just added a null check in stop function.

### CODE REVIEW

**Comment by Geokureli** [comment]
can you provide a reliable test case that reproduces this issue?

**Comment by TheoDevelops** [comment]
> can you provide a reliable test case that reproduces this issue?

```haxe
        if (flick != null){
            flick.stop();
        }

        final name = romGrp.members[select].name;

        if (name == 'empty') {
            romText.visible = true;
            flick = FlxFlicker.flicker(romText, 0.4 * 6, 0.4, false);
            return;
        }
```

that is the only place where the flick variable is used,
it gave me null object reference because the object was null,
and it was not

**Comment by Geokureli** [comment]
> it gave me null object reference because the object was null, and it was not

It really seems like the object is null and flick is being stoped after its completed and destroyed. Note that even though 'romText' isnt null or destroyed, flick.object  can still be null. If you were to trace flick.object i bet its null.

Rather than storing flick and calling stop, i recomend just calling [FlxFlicker.stopFlickering](https://github.com/HaxeFlixel/flixel/blob/797fa1395c7fba4515dd6d8766f2d78f2948269f/flixel/effects/FlxFlicker.hx#L77) or check FlxFlicker.isFlickering, or just check `if(flick.object != null)`.

Typically using or calling a method on a destroyed object is a mistake and we want devs to know when they make a mistake, since silencing the error may add confusion about whats actually happening, and can cause other issues down the road based on false assumptions

**Comment by Geokureli** [comment]
Closing, use the suggested fixes, above

**Pull request closed without merging**
