### PR TITLE
Add disabled status to FlxButton

### LINKED ISSUE #3083: Add disabled status to FlxButton
A very common feature that is missing from FlxButton which I think would be beneficial to have: A DISABLED state for FlxButton which would make the button ignore inputs and be displayed as being unable to be clicked (greyed out).

### PR DESCRIPTION
**Pull request by itulau**
Implements a DISABLED status for FlxButton. When a FlxButton is in this state mouse and input overlap will be ignored.

Small demo on which I tested this feature 
[demo-disabled-flxbutton.zip](https://github.com/HaxeFlixel/flixel/files/14624254/demo-disabled-flxbutton.zip)

Tested on HTML5 and Linux, which are the only platforms I currently got working Flixel in general.
demo

Closes #3083

Note: sprite "highlighted" status looks different for some reason in the preview, but compared side by side in Aseprite and they are the same.

### CODE REVIEW

**Comment by Geokureli** [comment]
Can you check flixel-ui and see if things that extend FlxButton don't break with normal use?

**Comment by Geokureli** [comment]
I tested this with Flixel-ui on a couple demos, no issues, I added FlxButtonState, which will cause some deprecation warnings on flixel-ui and flixel-addons, I have changes prepared on those repos to fix this

**Comment by itulau** [comment]
Ok, ping me when I can I open a PR to merge such changes. Or you prefer I open it right now and you handle it from there?

**Comment by Geokureli** [comment]
> Ok, ping me when I can I open a PR to merge such changes. Or you prefer I open it right now and we handle it from there?

Flixel-ui is ready, be sure to backmerge dev into your branch

**Comment by Geokureli** [comment]
> uh oh, ok!
> 
> I was checking flixel-ui myself and I've noticed a few things that needed to change to accomodate for this new status, but I didn't have the time to test them out
> 
> [itulau/flixel-ui@601bf1f](https://github.com/itulau/flixel-ui/commit/601bf1fe0c2cacc0bdf0773a4d9606c134f158f7)

Also @itulau be sure to use feature branches rather than your itulau/dev branch

**Comment by itulau** [comment]
> > uh oh, ok!
> > 
> > I was checking flixel-ui myself and I've noticed a few things that needed to change to accomodate for this new status, but I didn't have the time to test them out
> > 
> > [itulau/flixel-ui@601bf1f](https://github.com/itulau/flixel-ui/commit/601bf1fe0c2cacc0bdf0773a4d9606c134f158f7)
> 
> Also @itulau be sure to use feature branches rather than your itulau/dev branch, this makes things a little easier for me when I'm inspecting contributions

Yes, don't worry. I pushed the changes to my dev branch by mistake in a rush, but I'll be sure to use a feature branch like this PR.

**Pull request merged**
