### PR TITLE
[WIP] Input FlxText

### PR DESCRIPTION
**Pull request by MSGhero**
Functionality on not-Flash requires https://github.com/openfl/openfl/pull/1894

Looking for any input (ha, get it?). Only other thing I was thinking about was click-n-drag to select.

### CODE REVIEW

**Comment by Gama11** [comment]
So this is done, apart from waiting on that OpenFL PR to be merged? Or why the `[WIP]`?

**Comment by MSGhero** [comment]
I've been using it without any problems, but I figured it would be WIP until it's more fully functional. I think the click n drag to select is the only major thing, but that could also be a separate PR.

**Comment by Gama11** [comment]
Hm, doesn't look like the OpenFL side of this is going anywhere..

**Comment by MSGhero** [comment]
Yeah I haven’t had time to look into dealing with multiple stages. Feel free to close it if you think that’s better for now

**Comment by Gama11** [comment]
Closing for now until OpenFL actually enables this to work.

**Pull request closed without merging**
