### PR TITLE
Update FlxSprite.hx

### PR DESCRIPTION
**Pull request by greysondn**
Long story short, I'm told the savings exist primarily for flash. Let's update the docs.

### CODE REVIEW

**Comment by greysondn** [comment]
Woops, wrong base branch, sorry. Had just done it as a quick edit on github. Should be pointing at dev now.

**Comment by Gama11** [comment]
"Flash targets" is not really the right way to phrase it, it matters when _blitting_ is used (Flash, HTML5 Canvas).

**Comment by greysondn** [comment]
Another commit or redo so it's only one commit?

**Comment by Gama11** [comment]
Doesn't matter, they're squashed into one on merge.

**Comment by greysondn** [comment]
One word change done.

**Comment by greysondn** [comment]
Deleting source fork. Wish they could all be this painless. Be well.

**Pull request merged**
