### PR TITLE
Flixel Camera shader support functions

### PR DESCRIPTION
**Pull request by nom-lol**
check this out!

### CODE REVIEW

**Comment by xLoffi** [comment]
cums

**Comment by xLoffi** [comment]
this stuff good!!!

**Review by EyeDaleHim — CHANGES_REQUESTED** [review]
Why is this here?
```haxe
public static var defaultHUD(get, set):Array<FlxCamera>;
```

**Comment by Geokureli** [comment]
this PR reverts #2652 and #2591. I'm not sure what actually you're trying to add, not sure what `defaultHUD` is for

I recommend starting over with a new branch created from laster dev

**Pull request closed without merging**
