### PR TITLE
Permit centering a sprite at its origin on a flxpath

### PR DESCRIPTION
**Pull request by 47rooks**
Currently when a FlxSprite follows a FlxPath it cannot center itself on the path at its center of rotation. This can lead to some odd visuals in tilemaps or when the path itself is visible. This change attempts to maintain backward compatibility with the existing mechanism for choosing the center point while providing a new way to control the center point. This would support eventual deprecation of the autoCenter property in the future.

### CODE REVIEW

**Comment by 47rooks** [comment]
These failures are on the nightly and look the same as those George posted about in discord a few days ago. Let me know if I need to do anything but for now it seems there is nothing for me to do on it.

**Comment by Geokureli** [comment]
1. CI is failing because openfl's asset system isn't compatible with nightly haxe, no worries there

This is a great change in the right direction, but I think we should go about it in a different way, It's a bit complicated to explain so I may just make some commits

**Comment by 47rooks** [comment]
I'm happy either way so long as I can use the sprite origin to align the sprite on the path.

**Comment by Geokureli** [comment]
would you be able to test this using whatever you were using before, and also test the new `sprite.path.centerMode = CUSTOM(sprite.origin);` as well?

**Comment by 47rooks** [comment]
I just tested this and it works fine in both my programs. CUSTOM is a nice touch. I was thinking about arbitrary placement but had not lit on this idea.

**Comment by Geokureli** [comment]
i still have a test I wanna do but before i do that, @47rooks , what do you think of just having a path.centerOffset point, and removing the the centerMode enum all together?

**Comment by 47rooks** [comment]
So rather than rescaling the offset it becomes like a hitbox update - after scaling it's up to the caller to set it themselves ?

**Comment by Geokureli** [comment]
I think there was a miscommunication, due to me rambling on and thinking out loud. I wanted to entertain the idea of just having an centerOffset value rather than the the enum, the issues I describe above were not issues with the approach used in this PR, but issues with that new idea. I just thought I should bring it up in case you had input, but I think the current change is the way to go.

I'll have this merged in a little bit

**Pull request merged**
