### PR TITLE
Adding enumerations for more blend modes. 

### PR DESCRIPTION
**Pull request by larsiusprime**
Pending this PR to openfl:
https://github.com/openfl/openfl/pull/803

### CODE REVIEW

**Comment by larsiusprime** [comment]
OpenFL has merged the dependent PR's, so this is safe now.

**Comment by Gama11** [comment]
Urm.. how safe is "safe"? I guess this is not on haxelib yet? Travis is failing anyway...

**Comment by larsiusprime** [comment]
They just put out a maintenance release today?

**Comment by Gama11** [comment]
Ok, cool (that was after my comment).

Still, this means we're not backwards compatible at all, and #if openfl here probably wouldn't be a bad idea.

**Pull request merged**
