### PR TITLE
Return FlxFlickers

### LINKED ISSUE #1553: FlxFlicker and FlxTimer.pause()?
I know there's superissue #1087 in the air, but in the meantime, would it break anything if I added pause/resume methods to `FlxTimer` and by extension `FlxFlicker`? Are there other classes to add that to?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/23415587-flxflicker-and-flxtimer-pause?utm_campaign=plugin&utm_content=tracker%2F254189&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F254189&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by MSGhero**
To be able to pause them n stuff. Closes the already closed #1553.

Breaking change, but I'm not sure if anyone really cares.

### CODE REVIEW

**Comment by MSGhero** [comment]
I'll figure out branches one of these days.

**Comment by Gama11** [comment]
The return types of the functions are still `Void` and `FlxObject` respectively - this code doesn't compile.

**Comment by MSGhero** [comment]
Fixed, forgot to copy them over.

**Comment by Gama11** [comment]
"Copy them over"? Sounds like you're doing it wrong. ;)

**Comment by Gama11** [comment]
And Travis is still failing:

`/home/travis/build/HaxeFlixel/flixel/flixel/effects/FlxFlicker.hx:45: characters 4-10 : Void should be flixel.effects.FlxFlicker`

**Comment by MSGhero** [comment]
What do you think? Return null or return the existing flicker?

**Comment by Gama11** [comment]
We definitely don't want to cause any unnecessary null exceptions.

**Comment by MSGhero** [comment]
Do you use the github client or the command line? I have github/flixel fork and haxe/lib/flixel git, but it'd be easier using just one.

**Comment by Gama11** [comment]
Neither - SourceTree. The GitHub client was quite shitty back when I tried it, missing lots of functionality. And the command-line is too tedious.

And yeah, I only have a single clone of the repo (or any repo really). You can just push to a different remote.

**Comment by MSGhero** [comment]
Thanks, I'll have to play around with this.

**Comment by MSGhero** [comment]
Haha github just announced this: https://desktop.github.com/

I think they heard you.

**Comment by Gama11** [comment]
Heh. Already been announced yesterday or so though. ;)

**Pull request merged**
