### PR TITLE
Update FlxText.hx

### PR DESCRIPTION
**Pull request by buckle2000**
Increase readability.

### CODE REVIEW

**Comment by buckle2000** [comment]
#1771

**Comment by Gama11** [comment]
Hm, ARBG border colors should be supported..

**Comment by Gama11** [comment]
Oh, right, you're using 3.3.12. Alpha support for border colors has been added in 4.0.0.

**Comment by buckle2000** [comment]
@Gama11 
Be more precise, I was using `flixel: 3.3.12 [4.0.0]`.
Which is the actual version number?
default

**Comment by Gama11** [comment]
You have both 3.3.12 and 4.0.0 installed, but 4.0.0 is active (since it's within square brackets).

**Comment by Gama11** [comment]
Hm, transparency does seem to work, but it also appears to create a gray background for the text...

```haxe
package;

import flixel.FlxState;
import flixel.text.FlxText;
import flixel.util.FlxColor;

class PlayState extends FlxState
{
	override public function create():Void
	{
		var text = new FlxText(0, 0, 0, "Test");
		var transparentGreen = FlxColor.GREEN;
		transparentGreen.alphaFloat = 0.3;
		text.borderColor = transparentGreen;
		text.borderStyle = FlxTextBorderStyle.OUTLINE;
		add(text);
	}
}
```

**Comment by buckle2000** [comment]
But just borders can be transparent, not the fill color (main color) of text.
Due to poor flash API design. 
Also, please check this if you have not: #1771

**Comment by buckle2000** [comment]
Fixed a stupid error.

**Pull request closed without merging**
