### PR TITLE
FlxCamera.stopFade, stopFlash, and stopShake

### PR DESCRIPTION
**Pull request by CaptainBaldi**
Allows stopping of specific camera effects.

### CODE REVIEW

**Comment by CaptainBaldi** [comment]
> I'd rather just have a stop function for each effect, than an arg

Done

**Comment by Geokureli** [comment]
Thanks!

**Comment by CaptainBaldi** [comment]
@Geokureli when adding the new functions I forgot to remove the addition of `StringTools` used for the previous implementation, will this be a problem?

**Comment by Geokureli** [comment]
done

**Pull request merged**
