### PR TITLE
FlxTween#cancelTweensOf(), closes #1458

### LINKED ISSUE #1458: Kill all tweens of
TweenLite has a static function like this, and it would be good to have to avoid null object refs when something gets destroyed during its tween.

My question is, since this only affects VarTweens but needs access to the Tween Manager's private list of tweens AND VarTween's private `object`, which one should be exposed? Should it be `FlxTween.killTweensOf(obj)` or should it go into `FlxDestroyUtil`?

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9786623-kill-all-tweens-of?utm_campaign=plugin&utm_content=tracker%2F254189&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F254189&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by MSGhero**
#1458

I chose to make it manual adding and removing/canceling tweens instead of automatic so performance wouldn't be affected.

Usage would be like
```haxe
var tw = FlxTween.num(..., { onComplete : FlxTween.unregisterTween.bind(_, this) }, ...);
FlxTween.registerTween(tw, this);

override public function destroy():Void {
     super.destroy();
     FlxTween.cancelTweensOf(this);
}
```

### CODE REVIEW

**Comment by Gama11** [comment]
Looks useful, but at the same time it seems like a somewhat awkward workaround for tweens not being added to `FlxBasic` / `FlxObject` in the first place (which would also solve issues regarding substate pausing etc discusses in #1087). That would be quite a big refactor though...

**Comment by MSGhero** [comment]
Yeah @Beeblerox said this would be part of a refactor later on. I need the functionality now, and I figured I'd post how I did it.

**Comment by JoeCreates** [comment]
I use something along these lines to ensure I don't have multiple tweens fighting over the same object. The implementation of mapping objects to a tween in the same, but I also have an `exclusiveTween` method, which is identical to `FlxTween.tween` except you also pass it the dynamic key. When you `exclusiveTween` something, it automatically cancels the tweens with the same key.

This prevents things jittering and breaking when you, for example, have a tween pan the camera from one scene to another, but the user presses a button to tween back to the first scene before the first tween has finished.

Could this perhaps be worked into flixel, too?

**Comment by MSGhero** [comment]
How do you remove the key-val of the tween ends normally? Do you search through all the pairs looking or is it manual?

I had something automatic like that, but it didn't seem very performant.

**Comment by JoeCreates** [comment]
@MSGhero I didn't automate the removal. For the most past I just left the tweens in the map even after they were finished, seeing as it's fine to cancel an already finished tween. I haven't had any need to remove them, yet, seeing as I have mainly used this for UI with a finite number of elements, and so the map is generally small. It's useful to be able to manually remove them, of course. I just haven't needed to remove them at all , yet.

**Comment by MSGhero** [comment]
I was thinking in terms of garbage collection. You have the tween and the object it references chilling in the map.

**Comment by JoeCreates** [comment]
@MSGhero It's not something I've needed to consider yet, due to how frequently I reuse those objects.

**Comment by MSGhero** [comment]
I don't like this pull anymore. I'll leave #1458 up so it gets remembered, but I don't think anyone wants to *have* to bind a function and waste an onComplete to use it.

A proper way to do this should be a lazily created "tween manager" inside of each FlxObject and maybe an optional `AddTweenTo:FlxObject` parameter in the tween methods. Idk. 4.0.0 stuff.

**Pull request closed without merging**
