### PR TITLE
add `FlxInputText` to the flixel.text package

### PR DESCRIPTION
**Pull request by ShaharMS**
This is a patched version of FlxInputText that doesnt crash on native when 2 spacebars are pressed/multilines on JS.

This can be pulled right now (works as intended), and i can polish it later.
Whats offerred now:

basic input
correct word wrapping
cross platform multiline

what isnt offered now:

multi-language input
RTL on non-JS platforms

### CODE REVIEW

**Comment by ShaharMS** [comment]
i still need to add documentation and remove some boilerplate

**Comment by ShaharMS** [comment]
i just realized i haven't handled input from mobile anywhere in my code...

i did on a **heavily** modified version of FlxInputText, but that one wasn't as stable, so i decided to start development on an older, but stable mod. stuff i need to change/handle:

 - change input listener from openfl to lime (multilingual input)
 - focus on mobile
 - soft keyboard support
 - remove `_charBoundaries` as its not needed
 - add some more convenience functions and fields (`getCaretIndexUnderMouse()`, more listener fields, make key callback intuitive)

**Comment by Geokureli** [comment]
This shouldn't go in vanilla flixel, this should replace [the current FlxInputText in flixel-ui](https://github.com/HaxeFlixel/flixel-ui/blob/master/flixel/addons/ui/FlxInputText.hx). Also, you should make a demo for this in [Flixel-Demos](https://github.com/HaxeFlixel/flixel-demos). Something that showcases all of the features, not only to help newcomers, but also so we can test them all on all targets with Github actions and manual testing

**Review by Geokureli — CHANGES_REQUESTED** [review]
changes listed in previous comment

**Comment by Geokureli** [comment]
Changes requested was what I set this PR status to. this should definitely go in Flixel UI and replace the existing one there. make a PR on that repo: https://github.com/HaxeFlixel/flixel-ui

**Pull request closed without merging**
