### PR TITLE
check farbling, prevent infinite loops and warn the dev

### PR DESCRIPTION
**Pull request by Geokureli**
I'm all ears for a better name than `FlxG.html.farblesImages`, all my ideas were stupidly long. It comes from [this article by Brave](https://brave.com/privacy-updates-4/).

This is not a perfect solution, but IMO it is a decent temporary one. In the long run we should either get the default font some other way than `fromXNA`, perhaps `fromAngleCode`.

related to #2285

### CODE REVIEW

**Comment by MSGhero** [comment]
Well that's annoying

**Comment by Gama11** [comment]
Does Brave have enough of a market share that this matters?

**Comment by Geokureli** [comment]
I'm getting a lot a people reporting brave errors to me, I think it's gaining popularity and even if it doesn't I think anti-fingerprint practices like this are becoming a trend. I know little of how browsers work, but I fear that internet security software or plugins could bring this problem to more common browsers

**Comment by Geokureli** [comment]
https://en.wikipedia.org/wiki/Usage_share_of_web_browsers
Brave numbers are likely low. but it's hard to tell because `Browser.navigator.userAgent` doesn't even contain the word brave in it when playing on brave.

also this PR isn't blocking me, now that I know how to detect farbling I can display a message to the user to turn off shields

**Comment by MSGhero** [comment]
The infinite loop check should happen regardless. What about if the `while` hits the "infinite" condition, then we know(?) it's farbled and then warn or error? It seems like something that should be on the openfl level tbh

**Comment by Geokureli** [comment]
yeah, we could have it check when it getPixels beyond the bounds of the image and warn. I'm not familiar enough with this code to know whether there would be false positives, though

**Comment by Gama11** [comment]
I'm inclined to close this for now as long as we don't have more reports of this being an issue or it affects more browsers. From my perspective it seems like a rather hacky workaround specifically for a browser with a tiny market share.

**Pull request closed without merging**
