### PR TITLE
FlxSave: Fixes for latest openfl

### PR DESCRIPTION
**Pull request by larsiusprime**
Latest OpenFL removes the need for the #if flash stuff

### CODE REVIEW

**Comment by Gama11** [comment]
That would break compatibility with older OpenFL versions though, right?

**Comment by larsiusprime** [comment]
Ah, I guess so.

**Comment by larsiusprime** [comment]
This should be compatible with both old and new versions of OpenFL.

**Comment by Gama11** [comment]
Ah, so this is actually required for new openfl versions and not just cleanup?

Shouldn't the defines use `||` rather than `&&`?

Never really sure what to do with breaking openfl changes as we don't define a "minimum required version" with it, unlike Haxe. I guess it's better to stay compatible than not...

**Comment by larsiusprime** [comment]
Yeah, it is actually a requirement for the latest stuff.

And I'm *pretty* sure that the defines should be using ```&&```. If you're using the latest version of OpenFL, everything's nice and unified, including on flash (and js).

It's only using previous versions of OpenFL that the # if flash, #if js, blocks are still required.

**Comment by Gama11** [comment]
How can the flash behavior have changed? Shouldn't the code that flash needed before OpenFL 3.4.0 still be needed?

**Comment by larsiusprime** [comment]
See:

https://github.com/openfl/openfl/commit/7ac3b7dc71a8d9ffa9a314988230ffb6fd3a7732
https://github.com/openfl/openfl/commit/cd9c1eaa010def8e9778e9f7fd638e8114711d82

**Pull request merged**
