### PR TITLE
Fix platforms antialiasing issues & update logos

### PR DESCRIPTION
**Pull request by ACrazyTown**
I've noticed that the platforms image was recently updated to get rid of the background.
However it seems that by getting rid of the background the antialiasing of the logos got weirdly distorted and were quite blurry.

So I've updated the platforms image to fix the antialiasing issues, and also updated some logos like the Windows logo.

Comparison:
BEFORE
platforms (1)

AFTER
platforms

### CODE REVIEW

**Comment by Geokureli** [comment]
I hadn't noticed this until I saw @MrClogsworthYT 's snippets icon, which also seemed to have weird edges. What image editor are you using to make these, MrClog?

**Comment by MrClogsworthYT** [comment]
> I hadn't noticed this until I saw @MrClogsworthYT 's snippets icon, which also seemed to have weird edges. What image editor are you using to make these, MrClog?
background eraser in play store

What I have no money man

**Comment by Geokureli** [comment]
> background eraser in play store
What I have no money man

lol not judging

**Comment by MrClogsworthYT** [comment]
> > background eraser in play store
> > What I have no money man
> 
> lol not judging

Would have been funnier if you said
"Don't we all?"

**Pull request merged**
