### PR TITLE
FlxGroup: fix recursion in forEachOfType(), closes #1876

### LINKED ISSUE #1876: FlxGroup.forEachOfType recursive part not working
- **Flixel version:** 4.1.0
- **OpenFL version:** ?.?.?
- **Lime version:** ?.?.?
- **Affected targets:**

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
		var mastergroup:FlxGroup = new FlxGroup();
		var subgroup:FlxGroup = new FlxGroup();
		
		var testsprite:FlxSprite = new FlxSprite();
		var testsprite2:FlxSprite = new FlxSprite();
		var testsprite3:FlxSprite = new FlxSprite();
		var testsprite4:FlxSprite = new FlxSprite();
			
		mastergroup.add(testsprite);
		mastergroup.add(testsprite2);
		
		mastergroup.add(subgroup);
		subgroup.add(testsprite3);
		subgroup.add(testsprite4);
			
		mastergroup.forEachOfType(FlxSprite, this.traceSprite, true);
	}
	
        public function traceSprite(MySprite:FlxSprite):Void
       {
              trace(MySprite);
       }
```

________________________________

**Observed behavior:**
When setting the recursive flag to true, subgroups of the respective group will still not be searched, despite what the function descriptiuon says. Therefore, only the testsprites 1 and 2 will be traced, the ones in the subgroup will be ignored.

**Expected behavior:**
Obviously, with Recursive set to true, one would expect 4 traces.

**The Problem**
```haxe
if (basic != null &&  Std.is(basic, ObjectClass))
```
This line will obviously not be true for a FlxGroup (as long as we are looking for FlxSprite or Strings or anything else not being a FlxGroup)

**Suggested Solution**

```haxe
/**
	 * Applies a function to all members of type Class<K>
	 * 
	 * @param   ObjectClass   A class that objects will be checked against before Function is applied, ex: FlxSprite
	 * @param   Function      A function that modifies one element at a time
	 * @param   Recurse       Whether or not to apply the function to members of subgroups as well 
	 */
	public function forEachOfType<K>(ObjectClass:Class<K>, Function:K->Void, Recurse:Bool = false)
	{
		var i:Int = 0;
		var basic:FlxBasic = null;
		
		while (i < length)
		{
			basic = members[i++];
			
			if (basic != null && Recurse && Std.is(basic, FlxGroup))
			{
				var group = resolveGroup(basic);
				if (group != null)
				{
					group.forEachOfType(ObjectClass, cast Function, Recurse);
				}
			}
			

			if (basic != null &&  Std.is(basic, ObjectClass))
			{
				Function(cast basic);
			}
		}
	}
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/35508958-flxgroup-foreachoftype-recursive-part-not-working?utm_campaign=plugin&utm_content=tracker%2F254189&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F254189&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by MSGhero**
Closes #1876 

Condition wasn't allowing groups to be traversed.

### CODE REVIEW

**Comment by Gama11** [comment]
A unit test would be nice I guess. :)

**Comment by MSGhero** [comment]
K

**Comment by Gama11** [comment]
This doesn't really test the functionality too much (no check whether it would fire for non-FlxObjects as the groups only contain FlxObject). It does check if recursion works correctly though, which is good enough I guess.

Thanks!

**Comment by MSGhero** [comment]
Oh what, I could have sworn I made it add something else in the sub function

**Pull request merged**
