### PR TITLE
FlxGamepad: add switch controller model enum

### PR DESCRIPTION
**Pull request by larsiusprime**
Just some enums that define the various ways the switch controllers can be used. Necessary if you're using the OpenFL switch backend, and might be useful for desktop if we ever get native desktop support for these models.

### CODE REVIEW

**Comment by larsiusprime** [comment]
Maybe... I'd have to review how I use it in practice to make sure it's not checked every frame or something like that. Fancy enums generate a lot of dynamic state on cpp targets.

**Comment by Gama11** [comment]
Yeah, that's roughly what it'd look like. Would make it easier to check if you're dealing with something Switch-related (only have to check one instead of 5 values), for instance.

**Comment by Gama11** [comment]
Any update on this?

**Comment by larsiusprime** [comment]
Ah, you're on a "fix all of Lars' orphaned merges" kick. I'll go ahead and make this change this week, haven't touched it yet. You still okay with the last agreed upon fix?

**Comment by Gama11** [comment]
Sure, I was mostly wondering if you're okay with it. :)

**Comment by larsiusprime** [comment]
Yeah, that approach is fine. When do you need this by?

**Comment by Gama11** [comment]
I mean, we just had a release, so there's not gonna be one for a while anyway.

**Comment by Gama11** [comment]
Is this even useful on its own, without the model ever being auto-detected as one of these values?

**Comment by larsiusprime** [comment]
I'll have to check; I figure I added this for a reason, probably in relation to some stuff that came up with lime-switch, which uses the gamepad information coming from the switch itself. We can discuss in the slack channel or discord if necessary.

**Comment by Gama11** [comment]
As we discussed, this doesn't make sense to be merged in the current state and will be revisited at some later date.

**Pull request closed without merging**
