### PR TITLE
Preliminary fix for #861

### PR DESCRIPTION
**Pull request by GimmickyApps**
Currently does nothing for html5, and still needs fixing somehow for scales < 1.

(I had incorrectly done this directly from my dev branch the first time.  I'm only resubmitting it because now it's its own branch proper.)

### CODE REVIEW

**Comment by gamedevsam** [comment]
This one looks good to me, any reason why we're deferring?

**Comment by GimmickyApps** [comment]
Mostly because it's incomplete.  For me, the real use case is being able to zoom out (scale < 1), and that needs some deeper fix, I think.

**Comment by Gama11** [comment]
Closing this since it's not going to be merged in an incomplete state.

**Comment by GimmickyApps** [comment]
Dang, I was hoping someone else could help complete it.  Well, maybe I'll dig into it some day

**Pull request closed without merging**
