### PR TITLE
Fix plus keybind on Mac

### PR DESCRIPTION
**Pull request by NeeEoo**
This allows pressing + on Mac. Might only work for Swedish Mac keyboards since i don't have a english keyboard

### CODE REVIEW

**Comment by NeeEoo** [comment]
I don't see why it would be closed, the ascii code 43 means +

**Comment by Geokureli** [comment]
> FlxKeys do not map to characters, they map to keyboard button locations which are labelled based on their location in the english keyboard layout

**Comment by NeeEoo** [comment]
What mac do you have?

**Comment by Geokureli** [comment]
US English Layout
image

https://keyshorts.com/blogs/blog/37615873-how-to-identify-macbook-keyboard-localization

**Comment by NeeEoo** [comment]
I mean mac model, because it worked when i had a 2017 model, but not my 2023 model

**Comment by Geokureli** [comment]
I do have a 2017, but then would this change break plus on 2017s

**Comment by NeeEoo** [comment]
It wouldnt break, pressing plus there would return a different keycode, which would return the key 61_187 which has no nativeCorrection mapping which then makes it point to FlxKey.PLUS (187) due to the code below

```hx
var code = _nativeCorrection.get(e.charCode + "_" + e.keyCode);
return (code == null) ? e.keyCode : code;
```

this pr is only if the key returns 0_43

**Comment by Geokureli** [comment]
aight let's test this, sorry for the misunderstanding

**Comment by NeeEoo** [comment]
I just placed a trace here to get the value

Skärmavbild 2023-12-15 kl  18 08 44

`trace(e.charCode + "_" + e.keyCode);`

And it does work with setting the layout to US and pressing the \` key it returns the code `61_187`

**Comment by Geokureli** [comment]
> And it does work with setting the layout to US and pressing the ` key it returns the code `61_187`

what if you press +?

**Comment by NeeEoo** [comment]
When i said i pressed the ` button, that is the key which is equal to + when im on us keyboard layout

**Comment by Geokureli** [comment]
> When i said i pressed the ` button, that is the key which is equal to + when im on us keyboard layout

It is not, refer back to the pictures I sent, plus is typically on the = key

**Comment by NeeEoo** [comment]
Pressing the + (=) key on us keyboard layout still works with this branch

**Comment by Geokureli** [comment]
thanks!

**Pull request merged**
