### PR TITLE
adjust game size according to display in fullscreen mode

### PR DESCRIPTION
**Pull request by buckle2000**
#1852

### CODE REVIEW

**Comment by Gama11** [comment]
https://travis-ci.org/HaxeFlixel/flixel/jobs/130177749

```
/home/travis/build/HaxeFlixel/flixel/flixel/FlxGame.hx:239: characters 20-37 : openfl._legacy.display.Stage has no field window
```

**Comment by buckle2000** [comment]
@Gama11

**Comment by Gama11** [comment]
So.. that just makes it compile, but it's still broken?

**Comment by buckle2000** [comment]
Well I don't know how to get fullscreen in openfl legacy so I just let it be in window mode.

**Comment by buckle2000** [comment]
I think I found a typo in `FlxBaseTilemap`

**Comment by Gama11** [comment]
You didn't. Tile is a type parameter.

**Pull request closed without merging**
