### PR TITLE
Allow force-complete for `FlxSplash`.

### PR DESCRIPTION
**Pull request by T1mL3arn**
Without this fix `preGameStart` signal is not dispatched in some cases.

```haxe
package;

class TestState extends flixel.FlxState {
  override function create() {
    trace('TestState create()');
  }
}
class Main extends Sprite {

  public function new() {
    super();
    
    trace(#if debug 'debug' #else 'release' #end);
    flixel.FlxG.signals.preGameStart.addOnce(() -> trace('DISPATCHED!'));
    addChild(new flixel.FlxGame());
    Flixel.switchState(new TestState());
  }
}
```

Outputs in release and debug differ (due to `FlxSplash`, it is skipped in debug), but expected to be the same.

```
Output in release:

source/Main.hx:28: release
source/Main.hx:11: TestState create()
```

```
Output in debug:

source/Main.hx:28: debug
source/Main.hx:30: DISPATCHED!
source/Main.hx:11: TestState create()
```

So it is possible to trigger state switching before splash sets `_gameJustStarted` and without this flag `preGameStart` is not called.

### CODE REVIEW

**Comment by T1mL3arn** [comment]
The fix does not interfere with arg in `FlxGame` constructor. If user intentionally skips the splash with the arg, it behaves the same way as without the fix - no splash no problem.

**Comment by T1mL3arn** [comment]
If user does not use `skipSplash` arg in `FlxGame.new` then this means "show the splash" which leads to a bug. If user sets this arg to `true` then splash is gone and that's fine - no splash no bug.

**Comment by T1mL3arn** [comment]
Btw this also fixes stale "HaxeFlixel" text.

```haxe
addChild(new flixel.FlxGame(0, 0, null, false));

// dalay is used to show more stalled objects
// with no delay it is just "HaxeFlixel" text
haxe.Timer.delay(() -> {
  Flixel.switchState(new flixel.FlxState());
}, 250);

// NOTE: must be compiled with release flag !
```
<details>
    <summary>Click to see screenshot</summary>
    
image

</details>

In the case when state switch happened before splash completes, the splash lefts its flash display objects on the stage.

**Comment by Geokureli** [comment]
I'm confused by your "stale text" issue becuase I don't consider your example to be reasonably expected code from a haxeflixel dev, is this the only type this bug happens, or have you seen this issue in a more practical project?

**Comment by Geokureli** [comment]
So it looks like I misread your original post, I missed the line  `Flixel.switchState(new TestState());`. assuming "Flixel" is supposed to be "FlxG", I'm curious why anyone would ever do this? is this an attempt to skip the splash screen early? If so, there are easier ways to accomplish that

**Comment by Geokureli** [comment]
I don't think we should allow people to skip the splash screen by calling switchState during, they should just make a new custom splash screen that allows for skipping, we can make this easier, by making FlxSplash more modular

**Comment by Geokureli** [comment]
In our upcoming flixel 6 [feature branch](https://github.com/HaxeFlixel/flixel/pull/2733) I've made FlxSplash more modular. I in response to this PR, I added [this](https://github.com/HaxeFlixel/flixel/pull/2733/commits/bbf509e53ac20c358626df7681d8345ce4d37c76) which allows you skip in the way you like, but the [prior commit](https://github.com/HaxeFlixel/flixel/pull/2733/commits/324acd4d930f58785d8e2ffe74647446ab3bc71b) allows you to extend FlxSplash and make a skippable version, only difference is that `preGameStart` and `postGameStart` are dispatched with the splash state rather than after, but this seems pretty easy to deal with

Example:
```hx
class Main extends openfl.display.Sprite
{
    public function new()
    {
        super();
        addChild(new flixel.FlxGame(()->new SkippableSplash(flixel.FlxState.new), true));
    }
}

class SkippableSplash extends flixel.system.FlxSplash
{
	public function new (nextState)
	{
		super(nextState);
	}
	
	override public function create():Void
	{
		super.create();
		
		#if FLX_KEYBOARD
		FlxG.keys.enabled = true;
		#end
	}
	
	override function update(elapsed:Float)
	{
		super.update(elapsed);
		
		final keysPressed = #if FLX_KEYBOARD FlxG.keys.justPressed.ANY #else false #end;
		final mousePressed = #if FLX_MOUSE FlxG.mouse.justPressed #else false #end;
		final touchPressed = #if FLX_TOUCH FlxG.touches.justStarted().length > 0 #else false #end;
		final gamepadPressed = #if FLX_GAMEPAD FlxG.gamepads.anyPressed(ANY) #else false #end;
		if (keysPressed || mousePressed || touchPressed || gamepadPressed)
			complete();
	}
}
```

**Comment by T1mL3arn** [comment]
>I'm confused by your "stale text" issue becuase I don't consider your example to be reasonably expected code from a haxeflixel dev, is this the only time this bug happens, or have you seen this issue in a more practical project?

I agreed that in a more real project probably no one encounters this problem. The bug was discovered when I started to use some state switching for quick tests:

```haxe
// normal startup code
addChild(new FlxGame(0, 0, InitialState));

// immediate state switch to test things
FlxG.switchState(new Foo());
// FlxG.switchState(new Bar());
```

And during such test I got null-pointer exception from third-party lib. The exception was thrown only in a release build, the reason for the exception is that the lib didn't initialize some of its data due to `preGameStart` was not fired. So looking at how these flixel things work I found `FlxSplash` do not cover the case when it is switched out before its completion (and that abnormal state switching is the reason why `preGameStart` is not fired and for openfl objects leftovers). And I fixed that with this pr.

>Edit: it also seems like this fixes the stale text issue inadvertently, we could fix it in a more robust way by removing the openfl display objects in destroy().

Yep, that code from `onComplete()` could be partially moved to `destroy()`

>So it looks like I misread your original post, I missed the line Flixel.switchState(new TestState());

Sorry my bad, forgot to rename it back, I personally use such renaming because it has less camel-case and it is faster to type. Btw, could this be add as an official typedef?

**Comment by T1mL3arn** [comment]
Tested `flxstate_new` branch and found no errors with abnormal switching from splash. Thanks!

**Comment by Geokureli** [comment]
> Sorry my bad, forgot to rename it back, I personally use such renaming because it has less camel-case and it is faster to type. Btw, could this be add as an official typedef?

No worries, also, I feel this. 90% of the time I type "FLxG" with a capital L, I suck at typing so much its a wonder i went into software dev in the first place

**Pull request closed without merging**
