### PR TITLE
FlxSound.onComplete docs fix

### PR DESCRIPTION
**Pull request by nightblade9**
Tested on HTML5 and it seems to work fine.

### CODE REVIEW

**Comment by nightblade9** [comment]
Can this be merged? It's just a trivial documentation change.

**Comment by Gama11** [comment]
I think this comment might be from a time when the HTML5 target wasn't really a consideration / working properly. This might have referred to Android instead, so I'd first like to verify that it works properly there as well.

**Comment by nightblade9** [comment]
@Gama11 okay, I can take care of that.

**Comment by nightblade9** [comment]
Verified that it works as expected on Neko, Android, and HTML5 targets.

**Comment by Gama11** [comment]
Thanks. :) Out of curiosity, I just checked the commit history, turns out this comment is 5 years old:

https://github.com/HaxeFlixel/flixel/commit/ad0b3403b73fd167ae8752d54e1f1f2410e16783#diff-8167fd9f960f8473f99664fcff7d2860R111

**Pull request merged**
