### PR TITLE
Removes private keyword from fields

### PR DESCRIPTION
**Pull request by nachoverdon**
As discussed here: https://github.com/HaxeFlixel/flixel/issues/1916

Removes every occurrence of the private keyword that is not a class, an interface, an enum or a comment, just variables and functions.

It also removes a lot of trailing whitespace from some files...

edit: We should also edit the haxe checkstyle config file so it yield when we use `private`, to avoid future additions.

### CODE REVIEW

**Comment by MSGhero** [comment]
Did you use VSCode? You also deleted the tabs in otherwise empty lines.

**Comment by nachoverdon** [comment]
I used Sublime Text with the TrailingSpaces plugin and I checked one by one the values before replacing them.

I didn't see anything regarding tabs/spaces on empty lines in the [code style guide](http://haxeflixel.com/documentation/code-style/), so I set the config to trim on save because why not.

I messed up by doing that? Why is it correct to have tabs on empty lines?

**Comment by Gama11** [comment]
I intentionally held off doing this until #2068 is merged to avoid merge conflicts (which is mentioned in the issue, although the PR ID changed since then: https://github.com/HaxeFlixel/flixel/issues/1916#issuecomment-250899794).

**Comment by Gama11** [comment]
As mentioned, this is better done separately later once the potential for merge conflicts is lower.

**Pull request closed without merging**
