### PR TITLE
Add FlxObject#setPositionUsingCenter()

### PR DESCRIPTION
**Pull request by Aleph0Null**
Added setPositionUsingCenter(), which is more convenient than setPosition() for some situations.

This is my first ever pull request. If this is ok, I have some ideas about introducing 'pivot' points on FlxObjects which generalize the origin and can be used for e.g. setting position, rotating around, connecting with other pivot points.

### CODE REVIEW

**Comment by Gama11** [comment]
Hm... I see how this can be useful, but it seems like a bit of a workaround for a proper pivot point / origin.

What do you think @Beeblerox? You had some plans to refactor origin right?

**Comment by sruloart** [comment]
I think https://github.com/HaxeFlixel/flixel/issues/923 these issues should be answered by something like this proposal: https://github.com/GoodBoyDigital/pixi.js/issues/997

Everything is relative :)

**Comment by Tiago-Ling** [comment]
+1000 to using the exact same properties that @sruloart linked! Having `origin`, `pivot` and `anchor` working as described would be awesome!

**Comment by larsiusprime** [comment]
Yeah I agree with @Tiago-Ling  and @sruloart, that would be amazing.

**Comment by Aleph0Null** [comment]
Regarding pivots and anchors, I was thinking more generally in fact. I wanted to be able to designate a set of named 'reference points' (Pivot may not be the best choice of name) on sprites (FlxObjects). Not just two for positioning and one for rotation, but any number the user wishes. You could then do stuff like:

setCurrentPivot(name:String)    //should be used when no pivot is specified. Maybe have two 'defaults': setCurrentPositioningPivot(), setCurrentRotationPivot()
addPivot(name:String, x:Float, y:Float)
addRelativePivot(name:String, referencePivots:Array<String>, weights:Array<Int>, offsetX:Float, offsetY:Float)  //adds a pivot at a weighted barycenter of other pivots. Useful for e.g. defining midpoints
setPositionUsingPivot(?name:String, x:Float, y:Float)
rotateAroundPivot(?name:String, angleChange:Float)
positionOnPivot(?name:String, target:FlxObject, ?targetPivot:String)
linkToPivot(?name:String, target:FlxObject, ?targetPivot:String)   //this not just changes the current position of the sprite, but should also preserve relative position and angle during future frames, until unlinked

When constructed, FlxObjects should come with default pivots "Center", "Top Left", "Bottom Left", "Top Right", "Bottom Right" (and maybe suitable aliases, and/or make them case insensitive.) These should change accordingly when the sprite is resized. User-defined pivots can be defined relative to these pivots.

The screen could also support pivots, so you can do things like anchor UI elements to window corners that stay at the corners when the window is resized.

-----

What bothers me is that setPosition() uses top left corner, which is less natural to me than using center). In particular, I have sets of sprites which share the same centers but have different top left corners. I'm currently using setPosition(...) { setPositionUsingCenter(...); }, setPositionUsingCenter(), setPositionUsingTopLeft(), in my local copy, thought I'd share the simplest addition that doesn't break stuff for others and see how it goes.

**Pull request merged**
