### PR TITLE
Loading Graphics should allow for Unique graphics

### PR DESCRIPTION
**Pull request by SeiferTim**
All of the methods that loaded graphic assets were assuming unique: false when there are cases where you may want to load them using unique: true

### CODE REVIEW

**Comment by Gama11** [comment]
Why did you open two pull requests for this?

**Comment by SeiferTim** [comment]
> Why did you open two pull requests for this?

I'm not sure how/why it did that - I changed 2 different files to solve the same/similar issues... (I'm still not 100% familiar with the way Github works)

**Comment by Gama11** [comment]
Well... could you fix it? ;)

Also:
- you added a new parameter to various methods without updating the doc comment (`@param`)
- a boolean parameter with a default value shouldn't have a `?`, there's no need for this to be a `Null<Bool>`

**Comment by SeiferTim** [comment]
I would love to fix it!

...I have no clue where to start...

How do I add another file to a Pull Request? Or do I need to cancel this one and do a new one?

**Comment by Gama11** [comment]
I mean, this is far from your first pull request, and there's plenty of learning resources for Git and GitHub...

**Comment by SeiferTim** [comment]
Closed and combined changes from #2370 into this PR... (I hope I did this right...!?)

**Comment by Gama11** [comment]
Yes, looks correct. 

However, I think just realized that this change might not actually be necessary. `FlxGraphic` should be a valid `FlxGraphicAsset`, so you could for instance do `FlxAtlasFrames.fromSparrow(graphic)`, where `graphic` was created via one of the `FlxGraphic.from*` methods - and each of those already accepts a `Unique` parameter. That avoids having to duplicate this everywhere, and it seems fair enough that it's a bit more verbose since this use case doesn't seem all that common. Thoughts?

**Comment by SeiferTim** [comment]
I see what you're saying... I wouldn't have thought to do that - but, I guess it works...

I don't think that having this options *hurts* anything, and it allows for slightly fewer steps in your code... 

```
var myFont = FlxBitmapFont.fromAngelCode(FlxGraphic.fromBitmapData("assets/my_font.png", true), "assets/my_font.xml");
```

vs

```
var myFont = FlxBitmapFont.fromAngelCode("assets/my_font.png", "assets/my_font.xml", true);
```

I think the new method is just a degree easier to grok without having to connect the dots... but.. yeah, I guess it's not really solving an problem that doesn't already have a solution...

**Comment by Gama11** [comment]
>I don't think that having this options hurts anything

The concerns I have are: 
- Longer parameter lists, which increases the complexity - for instance that `fromMonospace()` method already has quite a few params.
- If we expose `unique` everywhere, what about the other parameters the `FlxGraphic.from*()` methods have, like `Key` or `Cache`, or potential new ones in the future? At some point, "flattening" the parameters just doesn't scale anymore - there's a reason we pass around `FlxRect`s rather than having separate `x`, `y`, `width` and `height` params on every method that needs a rectangle.

`FlxGraphic` didn't exist when methods like `FlxSprite.loadGraphic()` were created, but if it did, `loadGraphic()` probably wouldn't have `Unique` and `Key` parameters.

So I'd prefer not to merge this.

**Pull request closed without merging**
