### PR TITLE
Watch Expressions

### PR DESCRIPTION
**Pull request by MSGhero**
Added watching the hscript-parsed output of an expression in the Watch window of the debug menu.

watchexpr
more watch expr

### CODE REVIEW

**Comment by MSGhero** [comment]
What's up with travis? All the tests are fine, but neko is `Done(1)`ing. I didn't break anything afaik.

**Comment by Gama11** [comment]
https://travis-ci.org/HaxeFlixel/flixel/jobs/118738285#L303

**Comment by MSGhero** [comment]
https://github.com/HaxeFlixel/flixel/blob/dev/flixel/system/debug/console/ConsoleUtil.hx#L60 ?

**Comment by MSGhero** [comment]
I cleared all my local changes, downloaded the 4 changed files, and got it working fine on flash...

**Comment by Gama11** [comment]
Run `haxelib run openfl build coverage flash -Dcoverage2` locally on the coverage test to repro that. The problem is that you're not checking whether hscript is included (`runCommand()` only exists in that case).

**Comment by MSGhero** [comment]
Forgot about that...

**Comment by Gama11** [comment]
Cool feature! :+1:

**Pull request merged**
