### PR TITLE
Skip extra listener for non-Flash platforms

### PR DESCRIPTION
**Pull request by DigiEggz**
Adding an extra listener can cause callbacks to fire twice in rapid succession, causing errors. The Flash version may still require this, so the listener is retained for that platform.

### CODE REVIEW

**Comment by DigiEggz** [comment]
Please see if this interferes with buttons. I did not experience any differences when `overlapFound` is removed and it allows the button to be interacted with using stageEvents.

**Comment by DigiEggz** [comment]
Checking `input.pressed` instead of `overlapFound` allows the button to fire "onUp" events when triggered by elements other than the pointer.

**Comment by DigiEggz** [comment]
> can you provide small, complete test case that highlights the benefit of this change?

Sure thing!

**Comment by DigiEggz** [comment]
I made another change to make sure it functions correctly when the `allowSwiping` property is set.

[Demo.zip](https://github.com/HaxeFlixel/flixel/files/14181751/Demo.zip)

Here's a simple project that includes a `FlxButton` and a `FlxUIButton`. Clicking on any button should print text to the console. Pressing the **X** key or Enter will trigger the UI button.  Pressing the **S** key will disable swiping on both buttons.

When you swap between the current the new code, everything should properly react. The primary benefit is that an extra event listener is no longer added to every button instance. I've noted some occasions where the event listener can cause the "onUp" event to be fired twice, which can cause issues. Please let me know if you encounter any differences or have any concerns.

Because of the order of handling, this may resolve #1370.

**Comment by Geokureli** [comment]
I haven't checked the demo yet, but one fear i have pertains to this:
```hx
/**
* Using an event listener is necessary for security reasons on flash -
* certain things like opening a new window are only allowed when they are user-initiated.
*/
```
I've also experienced similar restrictions on browsers

**Comment by DigiEggz** [comment]
I left the onUp check for Flash since it likely still requires it, so Flash should function the same. The extra code added to `updateStatus()` was to fix a dragging issue introduced by the listener-less code.

The end goal is for buttons to function as they currently do, but without an extra event listener, freeing up memory and preventing execution order errors.

**Comment by Geokureli** [comment]
> I left the onUp check for Flash since it likely still requires it, so Flash should function the same

Again, I've noticed the same requirements on browsers meaning html5 should not have this removed

**Comment by DigiEggz** [comment]
> > I left the onUp check for Flash since it likely still requires it, so Flash should function the same
> 
> Again, I've noticed the same requirements on browsers meaning html5 should not have this removed

Oh, I see what you're saying! I thought you meant browsers as in Flash within a browser. I can continue to test HTML5 functionality between different browsers.

What would be a good test case for this? When it says open a new window, does it mean something like `FlxG.openURL()`?

**Comment by Geokureli** [comment]
> What would be a good test case for this? When it says open a new window, does it mean something like `FlxG.openURL()`?

Yeah i've specifically seen this error when opening a url, I'd also like to know more about this issue about events firing twice before I make a change like this for all projects. perhaps this should be an opt-in setting?

**Comment by DigiEggz** [comment]
So far I've had no issues on Firefox or Chrome when using openURL. It's been hard to replicate, but there are times when a button callback changes a graphic and opens a substate, the graphic is null for a second and an OpenFL null graphic crash occurs.

I noted that not adding the additional onUp callback listener stopped this from happening. Other than for Flash, it made sense to not add an extra callback if it was no longer necessary. Let me know if you have any issues with HTML5.

What would be the best way to make this opt-in?

**Comment by Geokureli** [comment]
TBH the open url issue is something that has come and gone once or twice with various security updates for browsers, at different times for different browsers.

Chrome has a domain whitelist and blacklist for this setting:
Screenshot 2024-02-10 at 12 06 19 PM

**Pull request closed without merging**
