### PR TITLE
Expose sound length.

### PR DESCRIPTION
**Pull request by IBwWG**

### CODE REVIEW

**Comment by Gama11** [comment]
Travis is failing:

```
Class: flixel.system.frontEnds.SoundFrontEndTest x.x
    ERROR: massive.munit.UnhandledException: Invalid field access : get_length at flixel.system.frontEnds.SoundFrontEndTest#testLoadInvalidSoundPathNoCrash at flixel/system/FlxSound.hx (319)
	at flixel/system/frontEnds/SoundFrontEnd.hx (124)
	at flixel/system/frontEnds/SoundFrontEndTest.hx (22)
	at massive/munit/TestRunner.hx (330)
    ERROR: massive.munit.UnhandledException: Invalid field access : get_length at flixel.system.frontEnds.SoundFrontEndTest#testPlayMusicInvalidSoundPathNoCrash at flixel/system/FlxSound.hx (319)
	at flixel/system/frontEnds/SoundFrontEnd.hx (92)
	at flixel/system/frontEnds/SoundFrontEndTest.hx (16)
	at massive/munit/TestRunner.hx (330)
```

**Comment by IBwWG** [comment]
Yay Travis!  :)

**Comment by Gama11** [comment]
I'm actually quite surprised that there didn't seem to be a way to obtain the duration previously. Speaking of, maybe `duration` is a better name than `length`?

**Comment by IBwWG** [comment]
I was too :)

If you like.  Doesn't make a difference to me--tracks' durations are referred to as "lengths" in media players, generally.  Likely used in a music context only, anyway (c.f. https://github.com/IBwWG/flixel/blob/6937618cc2f9cc1c9aa58d75439a343873c94282/flixel/system/FlxSound.hx#L85 where it's assumed to be music if you're using the `time` field as well.)

**Comment by Gama11** [comment]
I'd like a third opinion on the naming. :)

**Comment by IBwWG** [comment]
OpenFL's opinion?  They called it length internally :)

**Comment by Gama11** [comment]
Not really OpenFL's decision, they just copied the Flash API. ;)

**Comment by Gama11** [comment]
Btw, do you want an invite to the HaxeFlixel slack? (would need your email)

**Comment by IBwWG** [comment]
Indeed...

**Comment by IBwWG** [comment]
Sure, that'd be great some time...I will PM you when I'm ready :)  thanks!

**Comment by Gama11** [comment]
PM me? Since when does GitHub have private messages? :)

**Comment by IBwWG** [comment]
Well, ya know...the equivalent...I thought it had a way to e-mail another user directly.  Hmm, not sure how I contacted the last person from here...

**Comment by Gama11** [comment]
You can find my email in the commit history. I think the forums have PMs too.

**Pull request merged**
